determine task directory appropriately

diff --git a/trunk/bin/dev.in b/trunk/bin/dev.in
--- a/trunk/bin/dev.in
+++ b/trunk/bin/dev.in
@@ -15,6 +15,94 @@ export DEV_VERSION=@PACKAGE_VERSION@
 #  - exit status '1' on error
 set_project_dir() {
     set_project_dir_() {
+        local last_dir=`pwd`
+        while true; do
+            if test -e .devrc ; then
+                break
+            fi
+            cd ..
+            local this_dir=`pwd`
+            if test x"$last_dir" = x"$this_dir"; then
+                break
+            fi
+            last_dir="$this_dir"
+        done
+        if ! test -e .devrc; then
+            echo "Could not find a dev project (a directory containing .devrc)!" >&2
+            return 1
+        fi
+        pwd
+    }
+
+    export DEV_PROJECT_DIR=`set_project_dir_`
+}
+
+# Search for a task directory according to the algorithm given in the wiki.
+#
+# Input:
+#  - $DEV_TASK_DIR (optional)
+#  - $DEV_TASK_DIR_ID (optional)
+#  - $DEV_PROJECT_DIR
+# Side-effects:
+#  - set $DEV_TASK_DIR (exported) to the task directory, or to an empty
+#    string if not found
+set_task_dir() {
+    export DEV_TASK_DIR
+
+    # return immediately if we've been given the task dir
+    if test x"$DEV_TASK_DIR" != x; then
+        return
+    fi
+
+    # if we have DEV_TASK_DIR_ID, then search with that
+    if test x"$DEV_TASK_DIR_ID" != x; then
+        search_task_dir() {
+            local last_dir=`pwd`
+            while true; do
+                if test -e "$DEV_TASK_DIR_ID"; then
+                    pwd
+                    break
+                fi
+                cd ..
+                this_dir=`pwd`
+                if test x"$last_dir" = x"$this_dir"; then
+                    break
+                fi
+                if test x"$this_dir" = x"$DEV_PROJECT_DIR"; then
+                    break
+                fi
+                last_dir="$this_dir"
+            done
+        }
+        export DEV_TASK_DIR=`search_task_dir`
+    else
+
+    # otherwise, look for a subdirectory of the project directory
+        search_task_dir() {
+            local last_dir=`pwd`
+            while true; do
+                cd ..
+                this_dir=`pwd`
+                if test x"$this_dir" = x"$DEV_PROJECT_DIR"; then
+                    echo "$last_dir"
+                    break
+                fi
+                last_dir="$this_dir"
+            done
+        }
+        export DEV_TASK_DIR=`search_task_dir`
+    fi
+}
+
+# Search up from the current directory to find a directory containing
+# '.devrc'.  This is the project directory.
+#
+# Side-effects:
+#  - set $DEV_PROJECT_DIR (exported) to the project directory
+# Output:
+#  - exit status '1' on error
+set_project_dir() {
+    search_project_dir() {
         last_dir=`pwd`
         while true; do
             if test -e .devrc ; then
@@ -34,7 +122,7 @@ set_project_dir() {
         pwd
     }
 
-    export DEV_PROJECT_DIR=`set_project_dir_`
+    export DEV_PROJECT_DIR=`search_project_dir`
 }
 
 # Enumerate the available subcommands
@@ -53,7 +141,7 @@ enumerate_subcommands() {
     test -z "$dir" && continue
     for cmd in $dir/*
     do
-      if [ -f $cmd -a -x $cmd ]
+      if test -f $cmd -a -x $cmd
       then
         echo ${cmd##$dir/}
       fi
@@ -74,7 +162,7 @@ find_subcommand() {
   IFS=':'
   for dir in $DEV_SUBCOMMANDS_PATH:$libdir/dev/subcommands
   do
-    if [ -f $dir/$subcommand -a -x $dir/$subcommand ]
+    if test -f $dir/$subcommand -a -x $dir/$subcommand
     then
       echo $dir/$subcommand
       break
@@ -107,6 +195,10 @@ source $libdir/dev/paths.sh
 
 # get DEV_PROJECT_DIR
 set_project_dir || exit 1
+set -x
+set_task_dir
+set +x
+exit
 
 # set up defaults and source configuration
 export DEV_SUBCOMMANDS_PATH="${DEV_PROJECT_DIR}/dev/subcommands"
@@ -114,7 +206,7 @@ export DEV_TASKS_PATH="${DEV_PROJECT_DIR}/dev/tasks"
 source "$DEV_PROJECT_DIR/.devrc" || exit 1
 
 # parse any options to 'dev' itself
-while [ ! -z "$1" ]
+while test ! -z "$1"
 do
   case "$1" in
     -h|help) usage;;
@@ -125,18 +217,18 @@ do
 done
 
 # if no subcommand was given, give usage message
-[ $# = 0 ] && usage
+test $# = 0 && usage
 
 # figure out the path of the subcommand
 subcommand="$1"
 shift
 cmd_path="`find_subcommand $subcommand`"
-[ "$cmd_path" = "" ] && usage 
+test "$cmd_path" = "" && usage 
 
 # source any utiity function libraries
 for fns in $libdir/dev/functions.sh $DEV_PROJECT/lib/dev/functions.sh
 do
-  [ -f $fns ] && source $fns
+  test -f $fns && source $fns
 done
 
 # finally, execute the subcommand
